### ISSUE TITLE
Model - Support for a block tile?

### ISSUE THREAD

**Issue by alan-s** [leorohr/simulus#103]
If tile is a block tile read from the map, treat as an occupied tile all vehicles have to go around?
Am I correct in saying this logic is near present in the simulator?  If not will it be or should this be removed from the editor?

**Comment by EbrahimMalek** [comment]
Currently, having a tile set as occupied without a vehicle occupying it is treated the same way as a traffic light. Vehicles will wait at this blockage rather than going around. In other words, having a block tile will involve the introduction of some new functionality in our simulator app.

**Comment by alan-s** [comment]
Ah I see.  So I'll leave it to you and Leo to let me know if this should remain.
