### ISSUE TITLE
Editor/MainApp - Block tile question

### ISSUE THREAD

**Issue by alan-s** [leorohr/simulus#112]
Paul's just implemented a removeAll eraser which requires that blockages are tagged with direction and laneno as with a lane.  Thinking about it, a block should be associated with a lane object more than a land one so the change is valid.

This requires some rework of Lane class and obviously the model.  A lane tile will store an attribute isBlock {true, false} to indicate that one tile in the lane is a blockage.

Leo agrees and I am currently making the changes in Editor branch after which he can make simulator changes.  Any thoughts from others?

**Comment by jerrylwang** [comment]
I agree, this should just work out fine.

**Comment by alan-s** [comment]
Leo I've updated and committed to editor branch.  Lane, Road and MapXML updated classes.  Save/load working correctly in editor app.  I will now check over UI logic in the Editor.

Please note there is a new XML schema.  I've consolidated the different attributes into one definition.  See https://github.com/leorohr/simulus/wiki/XML-Map-Definition

**Comment by alan-s** [comment]
Main app in editor branch is actually working fine.  I found out the problem was it was reading the old file format on default.  Simply replaced it with a new default map.
