### ISSUE TITLE
Trivial texture question

### ISSUE THREAD

**Issue by alan-s** [leorohr/simulus#130]
1. replace dirt/city type with a 'water' tile?  for no particular reason than visual appearance. 
2. use current texture or those in 'shortlisted' folder in resources?

to do:
debug mode redraws old tile colours and traffic lights.  repaint to correct tile colour based on final choice of tiles

**Comment by leorohr** [comment]
1. Replacing city with water sounds good.
2. I prefer for the shortlisted tiles.

**Comment by alan-s** [comment]
Done.  Please check the re-factoring hasn't broken anything.
