### ISSUE TITLE
Code - Cars queue up in an intersection

### ISSUE THREAD

**Issue by leorohr** [leorohr/simulus#16]
In heavy traffic, cars will not stop before an intersection but use the tile of the intersection to queue as well. 
Should this be removed or simply considered as one possible behaviour (e.g. greedy)?

**Comment by jerrylwang** [comment]
I agree, in this scenario we could change the colour of the car once it steps into to the intersection and remain the same colour thereafter ( just so we can make it obvious to identify which cars have been greedy and show this to the audience). 
Documentation on this part also need to be added.
