### ISSUE TITLE
Doc - Team collaboration, Roles, Gantt-Chart

### ISSUE THREAD

**Issue by leorohr** [leorohr/simulus#2]
How you will work together as a team: set out the roles you expect team members to play; how you will collaborate as a team; how you expect to handle the peer assessment; and how you will resolve conflicts (including, but not limited to, the peer assessment).

**Comment by alan-s** [comment]
Presently working on this section of the initial report and the timescale/gantt chart.  If you have covered methodologies in your software engineering modules e.g. waterfall, agile, etc please let me know so I can ask you some questions about it?  Particularly how you would classify our approach and if there was preference for any?

**Comment by leorohr** [comment]
Hi Alan,

sorry for the late response. If asked, I would classify our approach as iterative & incremental. Iterative because we have weekly feedback sessions (maybe we could say that we meet twice a week to make it sound better?) and incremental because we start with default and mandatory functionality and then build on top of this.
If references are required, you could quote the articles referenced in this wiki page: http://en.wikipedia.org/wiki/Iterative_and_incremental_development <http://en.wikipedia.org/wiki/Iterative_and_incremental_development>
;P

I would say that an agile approach is not necessarily suitable for a project with a tight schedule and a team completing consisting of non-full time developers, because agile approaches require a lot of communication and, of course, agility. All this can be difficult to do when all developers are full-time students and have a full schedule even without the group project. 

Any other opinions?

**Comment by leorohr** [comment]
Hi Alan,

sorry for the late response. If asked, I would classify our approach as iterative & incremental. Iterative because we have feedback sessions and incremental because we start with default and mandatory functionality and then build on top of this.
Quick references can be found here: http://en.wikipedia.org/wiki/Iterative_and_incremental_development http://en.wikipedia.org/wiki/Iterative_and_incremental_development
I would say that an agile approach is not necessarily suitable for a project with a tight schedule and a team completing consisting of non-full time developers, because agile approaches require a lot of communication and, of course, agility. All this can be difficult to do when all developers are full-time students and have a full schedule even without the group project. 

Any other opinions?

**Comment by alan-s** [comment]
Hi Leo,

Thank you for this input, I have merged it into the intial draft of section 2.

This is now uploaded in new folder in the "doc" section.  Could I please have comments taking in mind this is first draft, that needs trimming.  I'll look for comments on Facebook also.
