### ISSUE TITLE
Create Analytics Report

### ISSUE THREAD

**Issue by leorohr** [leorohr/simulus#25]
Optional:
We can let a user start an "Analysis Session" and from this point start tracking the metrics as described in #24. When the user ends this session, we can allow to export a report (xml, html?) about the observed metrics.

**Comment by alan-s** [comment]
How at present are data points stored?  For how long?  We could simply output to a csv?

**Comment by leorohr** [comment]
At present, only 100 data points are stored in memory (i.e. data of 50seconds). If we want to implement this feature, we should probably create a temp. file to put store the data points during simulation, that is either trashed when the simulator is shut down or persisted if the user wishes to export the data.

**Comment by alan-s** [comment]
Leo I am going to code up quick basic csv writer class, which all you'll need to do is pass the column header and values to append every time you update the charts etc...

**Comment by alan-s** [comment]
This is done in most part.  Simple csv export.  Does the job.
http://postimg.org/image/mx4z6so6x/
