### ISSUE TITLE
Java XML Map class

### ISSUE THREAD

**Issue by alan-s** [leorohr/simulus#34]
Class to load map (XML) files + save to

**Comment by alan-s** [comment]
I created a basic tile class based on talks we had about what the editor would record.  A tile is land, lane or intersection.  Lane tiles have direction.

Should this be scraped and the tile class already present in the simulator be used?

**Comment by leorohr** [comment]
Do you mean the TileXML class? The XML stuff should definitely be in a separate class; if it is the UI class that actually draws tiles on the canvas it might not be worth the effort of maintaining two implementations with very similar functionality.

**Comment by alan-s** [comment]
Leo and I discussed this today and agreed that for the simple XML view of the tile class, there is no need to merge into or use the more complicated tile class used by the model implementation.

**Comment by alan-s** [comment]
For further consideration.  Paul & I
