### ISSUE TITLE
Code - Per-car thread of control

### ISSUE THREAD

**Issue by leorohr** [leorohr/simulus#5]
Each car should be equipped with its own thread of control and clock in order to support advanced per-car behaviours. (See milestone description)
[Open for discussion]

**Comment by jerrylwang** [comment]
pseudo code for trafficLight/Intersection and car movement: 
if blockage() = true, then sleep(3000), check blockage, checkAvailableMovableDirection(), if blockage=false, move(Direction).

**Comment by leorohr** [comment]
Not doing that.
