### ISSUE TITLE
Editor - allow selection of prefefined grid sizes

### ISSUE THREAD

**Issue by alan-s** [leorohr/simulus#52]
40x40
60x60
80x80

**Comment by leorohr** [comment]
NxN meaning the number of tiles per row/column

**Comment by alan-s** [comment]
Not required pending any change from the model to handle varying grid size.

**Comment by alan-s** [comment]
Editor now supports different grid sizes.  we may need to get rid of 60 (not a factor of 800) and replace with 50 perhaps.
