### ISSUE TITLE
Editor - create pre-defined maps for each grid size

### ISSUE THREAD

**Issue by alan-s** [leorohr/simulus#53]

**Comment by alan-s** [comment]
Right so any thoughts on 2 maps per grid size(assuming grid size change being done in model) to create and commit into our resources folder?
Any suggestions for interesting maps that show possible a real world place? A map that might show of the strengths of the simulator?

**Comment by leorohr** [comment]
I’d suggest the map we currently use + one that has a couple of t-junctions or possible even a “junction” that is just a corner.

**Comment by alan-s** [comment]
I recreated the hash map using the new xml format manually so i'll upload that now for you to test but you might want to use your map create function to do it properly.

**Comment by alan-s** [comment]
welcome any 'interesting' maps you budding designers can generate.  if it looks interesting, or is a map with good talking points, etc, etc please share.  just dump into the "maps" folder and commit to git....
