### ISSUE TITLE
Truck Colors

### ISSUE THREAD

**Issue by leorohr** [leorohr/simulus#56]
In the current version in the ui_features branch, cars are coloured based on the user's choice in the combobox.
Should we have a second combobox for trucks or should trucks and cars just all be coloured based on that one combobox?

**Comment by alan-s** [comment]
I think it all depends on how you are doing time wise with implementing more important functionality although I do not think it would take much to add a separate combobox + logic for the trucks. Someone could purely be interested in how cars/trucks flow in relation to each other so making it separate would be useful.  Great job through on allowing the user select by speed and behaviour.

**Comment by paulbarella** [comment]
Would we want a user to be able to select the same colour for both cars and trucks?
Does changing the colour serve any real purpose or is it purely a cosmetic option just for the sake of having it?

**Comment by leorohr** [comment]
It is purely cosmetic and does not take more than 5 minutes to implement. My main concern was that the controls-panel could become cluttered if we add all these options. 
I'll think i'll add it for now and then we can take it out (or move it somewhere else) if there are too many options and sliders and buttons in the end.
