### ISSUE TITLE
Editor: Mouse Position != to Map Position when Window is enlarged

### ISSUE THREAD

**Issue by paulbarella** [leorohr/simulus#59]
Mouse position coordinate appears to be relevant to left-side of window rather than left-side of map

**Comment by leorohr** [comment]
Currently, the mainApp-window is not resizable. The editor-window could simply be set to a fixed size as well.

**Comment by paulbarella** [comment]
Yeah, that does work of course, but I'll spend a few minutes looking to fix it an alternate way that allows resizing.

**Comment by alan-s** [comment]
Fixed size window is set. No resize
