### ISSUE TITLE
Editor/Model - At max size of 80 x 80 lane markings not visable

### ISSUE THREAD

**Issue by alan-s** [leorohr/simulus#74]
may need to use a different image for this grid size.  ok at 60x60

**Comment by paulbarella** [comment]
This will be a quick fix, I'll just re-size the images to 80*80px and make the lines a little thicker.

**Comment by alan-s** [comment]
Not required pending any change from the model to handle varying grid size.

**Comment by alan-s** [comment]
Leo and I discussed and this is actually OK. at 40 x 40, normal full tile size. At 60 (if it remains), still fine.  At 80x80 no need to see individual lanes as its about overview and data collection, not so much about monitoring individual intersections.
